### ISSUE TITLE
Week1 - Exercise 1

### ISSUE THREAD

**Issue by dzvoti** [dzvoti/TFNC-Training#1]
| Activity                              | Description                                           |
|--------------------------|----------------------------------------------|
| 1.1 GitHub sign-up                    | [Create a GitHub account](https://github.com/)                  |
| 1.2 R download and installation       | [R download and installation](https://cloud.r-project.org/)            |
| 1.3 Rstudio download and installation | [Rstudio download and installation](https://posit.co/download/rstudio-desktop/) |
| 1.4 Git download and installation     | [Git download and installation](https://git-scm.com/downloads)                  |

**Comment by cchagumaira** [comment]
Asante sana Liberty!
