### ISSUE TITLE
Week 9 - Assignment

### ISSUE THREAD

**Issue by LuciaSegovia** [dzvoti/TFNC-Training#10]
Dear @mainuka, @Hoyce509 and @aalex27,

I hope this message finds you well and you had enjoyed today's session! 

I am writing to provide you with the details of this week assignment.

The objective of the assignement is to practice what we have learnt today. So, each one of you would need to complete the [fct_activity1.R](https://github.com/dzvoti/TFNC-Training/blob/main/Week-9/Materials/fct_activity1.R), as we have done together during our session. Once, you have populated the scipt you can submit them, and we will reveil the asnwers! 

I would appreciate it if you could review and complete the assignment by Tuesday, 14th. If you have any questions, you can pin @TomCodd or myself, and we will assist :)

Thank you for your time and dedication to this training program.

Kind regards,

Lucia :)

**Comment by Hoyce509** [comment]
Dear Lucia,
Thank you so much for today's session.
We will work on the assignment as instructed and share through Github.
Once again, thank you.

Cheers,

**Comment by mainuka** [comment]
Dear Lucia
The session was good and interesting. We will work on the assignment in due
time, and in case of any hurdle, we will communicate.
Regards
Aleswa

**Comment by LuciaSegovia** [comment]
Thank you very much @Hoyce509 & @mainuka for your enthusiam and participation. It was lovely meeting you!

Looking forward to see the assignments and, please let us know if you need help!

**Comment by mainuka** [comment]
Dear Lucia
I am done with my assignement
How can I share with you from R ? SHARED HERE
Kindly assist

**Comment by LuciaSegovia** [comment]
Hi Aleswa! 

You can go [here](https://github.com/dzvoti/TFNC-Training/tree/main/Week-9/Materials) and click in "Add a file" (see the picture) and upload it there. 

If you are having troubles doing it, let me know! And, we will find another way :)

Thank you!!

![add_file](https://user-images.githubusercontent.com/48588417/224310170-3fca9825-3303-4b78-b418-f11cb4e7baae.png)

**Comment by mainuka** [comment]
Got it, thanks!

**Comment by Hoyce509** [comment]
Hi Lucia,
I have uploaded my assignment to Github.
However, I am having a problem with question number 4 which is about
re-calculating the FE and Protein into mg and g respectively.

Thank you.

Hoyce

*Dr. Hoyce Amini Mshida (Ph.D.)*
*Research Scientist: Public Health & Nutritional Sciences,*
*Queen Elizaberth Scholar Allumni,*

*RISE by SUNDARA Research fellow, *

*P.O.BOX 977, Tanzania Food and Nutrition Center (TFNC), Dar es Salaam,
Tanzania*

*Mobile: +255 756 422 279/+255 657 422 379*

*Email: ***@***.*** ***@***.***>;  *

*Alternative Email: ***@***.*** ***@***.***>*

*ORC-ID: https://orcid.org/0000-0002-1738-6515
<https://orcid.org/0000-0002-1738-6515> *

**Comment by LuciaSegovia** [comment]
Hi @mainuka and @Hoyce509, 

Thank you and congratulations for submitting the assignment! 

@Hoyce509  I think your code is correct, but you need to convert the variables to numbers before doing the calculations.

Anyway, I will be uploading the solutions tomorrow, so you can have a look at them, and we can discuss it next week!

Thank you!!
Lucia

**Comment by Hoyce509** [comment]
Dear Lucia,
This is Awesome, thank you so much!

Regards,

*Dr. Hoyce Amini Mshida (Ph.D.)*
*Research Scientist: Public Health & Nutritional Sciences,*
*Queen Elizaberth Scholar Allumni,*

*RISE by SUNDARA Research fellow, *

*P.O.BOX 977, Tanzania Food and Nutrition Center (TFNC), Dar es Salaam,
Tanzania*

*Mobile: +255 756 422 279/+255 657 422 379*

*Email: ***@***.*** ***@***.***>;  *

*Alternative Email: ***@***.*** ***@***.***>*

*ORC-ID: https://orcid.org/0000-0002-1738-6515
<https://orcid.org/0000-0002-1738-6515> *

**Comment by rgoto55** [comment]
Dear All,

Well done to finish the assignment! Good job! 

Thank you, Lucia, for your wonderful support.

See you next week. 👍 

With best wishes,
Rie

**Comment by Hoyce509** [comment]
Dear Lucia,
Thank you for the feedback!
Hoping to see you in the coming sessions

Regards,
Hoyce

**Comment by mainuka** [comment]
Dear Lucia
I hope this mail finds you well.
One of our colleagues here at the institute wants to listen to videos on R
training weeks 1 and 2.
How can I assist her to get the video on her GitHub account, her user name
on GitHub is medainah
regards
Aleswa

**Comment by mainuka** [comment]
She has a ithub account bit not connected in here.
How can I share this in her github or use normal email address??
