### ISSUE TITLE
Week-10: Pre-session materials

### ISSUE THREAD

**Issue by LuciaSegovia** [dzvoti/TFNC-Training#15]
Hi @mainuka, @Hoyce509 & @aalex27 , 

I hope you had a great week and you are looking forward to our next session! We have prepared some pre-session materials for you.

Please find [here](https://github.com/dzvoti/TFNC-Training/blob/main/Week-10/Materials/data/tz_food-matches_v.1.0.0.csv) a dataset with the food matches for the food reported as consumed (food list) in the Tanzania National Panel Survey Extended Panel with Sex Disaggregated Data (NPS-DSS 2019-2020). 

The dataset consist of  5 columns:

- **itemcode**: it contains the food id. of the food consumed by the houshold as reported in the NPS-DSS 2019-2020.
- **item_desc**: it contains the food description of the food consumed by the houshold as reported in the NPS-DSS 2019-2020.
- **FoodName_3**: it contains the food description of the food item to be matched to in the food composition tables
- **wt**: it contains the weights used in the weighted mean, which is used for those items that are matched one to many. For example the item: "601 - ONIONS, TOMATOES, CARROTS AND GREEN PEPPER, OTHER VIUNGO" will be matches to 9 food items (e.g., "onion, raw", "carrots, raw", etc.) in the food composition tables.
- **N_HH**: it shows the number of households that reported consuming that food item. 

Please, get familiar with the dataset and start thinking about the food matches.

- Do you think that the food matches selected represents well what it is consumed in Tanzania?
- If not, what other foods would you add/remove/change to?

Finally, there are some foods without matches, can you think of what food items you would use? Could you identify any food matches in the [Tanzania FCT, 2008](https://www.hsph.harvard.edu/wp-content/uploads/sites/30/2012/10/tanzania-food-composition-tables.pdf) that will be a good match for those foods that have no matches? 

If you don't have the Tanzania FCT, 2008 stored in your computer, I recommend you to download it and add it to your "data" folder. 

Looking forward to seeing you tomorrow!

Thank you!

@TomCodd, @rgoto55 & Lucia

**Comment by mainuka** [comment]
Dear Lucia
this is well-noted and looking forward to the next session
Regards
Aleswa

**Comment by Hoyce509** [comment]
Dear Lucia,
This is noted for action.
Thanks.

Hoyce

**Comment by Hoyce509** [comment]
Dear Lucia,
I hope this email finds you well.
Yesterday I was able to access materials for week 10 via github.
Unfortunately, this morning I noticed that the materials are no longer
there.
Can you please assist on this? We need to work on the assignment given.
Thanks.

Regards,
Hoyce

**Comment by mainuka** [comment]
Dear Lucia and the team
We thank you too; the session was really educative, and personally, I
gained a lot.
Looking forward to the next session Despite the internet problem, the
recording has been a useful methodology for us following the session.
Regard
Aleswa

**Comment by LuciaSegovia** [comment]
Hi Aleswa, 

Thank you very much for your kind words, and very happy to hear! 

Looking forward to seeing you soon :)

Lucia
