### ISSUE TITLE
Week1-Exercise 2

### ISSUE THREAD

**Issue by dzvoti** [dzvoti/TFNC-Training#2]
| Action                  | Command                                            |
|----------------------|--------------------------------------|
| In Rstudio console type | `usethis::create_github_token()`                   |
| In your GitHub account  | `generate and copy  token`                         |
| In Rstudio console type | `gitcreds::gitcreds_set()`                         |
| In Rstudio console      | `paste token`                                      |
| In Rstudio terminal     | `git config --global user.name "YourGitHubUsername"`        |
| In Rstudio terminal     | `git config --global user.email "YourGitHubEmail@here.com"` |

**Comment by mainuka** [comment]
I don't understand what I am supposed to do, kindly can you make it clear

**Comment by mainuka** [comment]
hi
I have a problem with downloading the rstudio there is a message popping up
[image: image.png]
kindly assist
Aleswa

**Comment by cchagumaira** [comment]
> I don't understand what I am supposed to do, kindly can you make it clear

Hello there, did you manage to download RStudio and get it working?

**Comment by mainuka** [comment]
not real seem there are some component missing to reach an end 
![image](https://user-images.githubusercontent.com/122451232/212288439-037e014d-f53a-4942-b355-44f6b54eea57.png)

**Comment by cchagumaira** [comment]
Hello Aleswa,

Do you have time for a quick call so that I can assist you?

Best wishes

Chris

**Comment by mainuka** [comment]
![image](https://user-images.githubusercontent.com/122451232/212288688-76374aa4-da48-4900-aa7e-6633d005a435.png)
 since Tuesday it still keep on retrieving package installation   context

**Comment by mainuka** [comment]
Around 2 our time is ok

**Comment by mainuka** [comment]
maybe around 2 our time
Thank you, and I will appreciate it.

**Comment by cchagumaira** [comment]
Hello Aleswa,

Please use the following Zoom link at 14:00 your time


Best wishes

Chris

Chris Chagumaira is inviting you to a scheduled Zoom meeting.

Join Zoom Meeting
https://us02web.zoom.us/j/84000283930?pwd=RXpJc2FHUDZoR3BtUGMvd1c5aE9TQT09

Meeting ID: 840 0028 3930
Passcode: 717636

**Comment by mainuka** [comment]
thank you

**Comment by mainuka** [comment]
sorry Christ, still in another meeting. can we move to next week on Monday
at the same time?
Aleswa

**Comment by cchagumaira** [comment]
Hello Aleswa,

 Monday at 11:30 UK time (14:30 Tanzania time). Will that work for you?

Best regards

Chris

**Comment by mainuka** [comment]
very ok
thank you

**Comment by Hoyce509** [comment]
Dear Liberty,

Thank you for the assigned package.
However, my laptop does not accept R-64 bits, but further R- 32 bits.
Is it okay for learning purposes or is it a must to have a new R version?
Thank you.

Regards,
Hoyce

**Comment by dzvoti** [comment]
Hello @Hoyce509 

Thank you for completing the assignment. 

The R-32bit version will work well. No, It is not a must to have a new R version, we do not intend to use any version-specific packages at this point.

I hope that this is helpful.

Liberty

**Comment by Hoyce509** [comment]
Great.
Thank you.

Regards,
Hoyce
