### ISSUE TITLE
Week 4 Assignment Exercise

### ISSUE THREAD

**Issue by dzvoti** [dzvoti/TFNC-Training#4]
Through this exercise, you will revise the following concepts:

Creation of `vectors` and `factors`
Combination of vectors and factors into a `dataframe`
Inspection of `dataframe` structure using `str` function
Viewing `dataframe` contents using the `head` function.

@rgoto55 , @mainuka , @Hoyce509 , @aalex27  [Please access the exercise here](https://dzvoti.github.io/TFNC-Training/Week-4/week-4-assignment.html)

**Comment by dzvoti** [comment]
> Dear Liberty, Thank you for your email and assignment. We will work on it over the weekend. Have a good day. Regards, Hoyce

Thank you @Hoyce509

**Comment by dzvoti** [comment]
> Dear Liberty, Thank you for your email and assignment. We will work on it over the weekend. Have a good day. Regards, Hoyce
 Thank you @Hoyce509

**Comment by mainuka** [comment]
Thank you Liberty
we will work on it over the week end 
enjoy your week end
Aleswa

**Comment by mainuka** [comment]
### week four assignment, construction of dafa frame (df)

admin_reg <-c("Arusha", "Dar es salaam", "Dodoma", "Geita", "Iringa", "Kagera", "Katavi", "Kigoma", "Kilimanjaro", "Lindi")
str(admin_reg)
population <- c(1000000,2000000,3000000,1500000,1200000,110000,800000,600000,700000,500000)
str(population )
households <- c(100000,150000,200000,75000,60000,55000,40000,30000,35000,25000)
str(households)
example<-data.frame(admin_reg=c("Arusha", "Dar es salaam", "Dodoma", "Geita", "Iringa", "Kagera", "Katavi", "Kigoma", "Kilimanjaro", "Lindi"),
                    population=c(1000000,2000000,3000000,1500000,1200000,110000,800000,600000,700000,500000),
                    households=c(100000,150000,200000,75000,60000,55000,40000,30000,35000,25000))
print(example)
mean(population)
mean(households)

**Comment by dzvoti** [comment]
> ### week four assignment, construction of dafa frame (df)
> admin_reg <-c("Arusha", "Dar es salaam", "Dodoma", "Geita", "Iringa", "Kagera", "Katavi", "Kigoma", "Kilimanjaro", "Lindi") str(admin_reg) population <- c(1000000,2000000,3000000,1500000,1200000,110000,800000,600000,700000,500000) str(population ) households <- c(100000,150000,200000,75000,60000,55000,40000,30000,35000,25000) str(households) example<-data.frame(admin_reg=c("Arusha", "Dar es salaam", "Dodoma", "Geita", "Iringa", "Kagera", "Katavi", "Kigoma", "Kilimanjaro", "Lindi"), population=c(1000000,2000000,3000000,1500000,1200000,110000,800000,600000,700000,500000), households=c(100000,150000,200000,75000,60000,55000,40000,30000,35000,25000)) print(example) mean(population) mean(households)

Congratulations @mainuka  for this remarkably successful attempt keep it up.

**Comment by mainuka** [comment]
Asante mwalimu Liberty
Thank you our teacher Liberty
Aleswa

**Comment by dzvoti** [comment]
> Asante mwalimu Liberty Thank you our teacher Liberty Aleswa
> […](#)


Asante sana Aleswa.

**Comment by Hoyce509** [comment]
Wow,Liberty. you are catching swahili quickly.Big up to you.HoyceSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Liberty Mlambo ***@***.***> Date: 06/02/2023  16:20  (GMT+03:00) To: dzvoti/TFNC-Training ***@***.***> Cc: Hoyce509 ***@***.***>, Mention ***@***.***> Subject: Re: [dzvoti/TFNC-Training] Week 4 Assignment Exercise (Issue #4) 



Asante mwalimu Liberty Thank you our teacher Liberty Aleswa

…



Asante sana Aleswa.



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/dzvoti/TFNC-Training/issues/4#issuecomment-1419072083",

"url": "https://github.com/dzvoti/TFNC-Training/issues/4#issuecomment-1419072083",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by mainuka** [comment]
hellow do we have a link to joint for today session?
If yes where can I get it.

**Comment by Hoyce509** [comment]
Hi Aleswa,
If I haven`t mistaken, we are going to use the same link used in the last
session.

Hoyce

**Comment by Hoyce509** [comment]
admin_regions <- c("Arusha","Dar es Salaam","Dodoma","Geita","Iringa","Kagera","Katavi","Kigoma","Kilimanjaro","Lindi") 
> str(admin_regions)
 chr [1:10] "Arusha" "Dar es Salaam" "Dodoma" "Geita" "Iringa" "Kagera" ...
> population <- c(1000000,2000000,3000000,1500000,1200000,1100000,800000,600000,700000,500000)  
> str(population)
 num [1:10] 1000000 2000000 3000000 1500000 1200000 1100000 800000 600000 700000 500000
> households <- c(100000,150000,200000,75000,60000,55000,40000,30000,35000,25000)
> str(households)
 num [1:10] 100000 150000 200000 75000 60000 55000 40000 30000 35000 25000
> mean(population)
[1] 1240000
example <- df(admin_regions=c("Arusha","Dar es
Salaam","Dodoma","Geita","Iringa","Kagera","Katavi","Kigoma","Kilimanjaro","Lindi"),                    
+ population=c(1000000,2000000,3000000,1500000,1200000,1100000,800000,600000,700000,500000),households=c(100000,150000,200000,75000,60000,55000,40000,30000,35000,25000)) 
**summary(example)
Error in object[[i]] : object of type 'closure' is not subsettable**

**Comment by Hoyce509** [comment]
Dear Liberty,
Kindly receive my assignment.
I tried to command "summary(example)" to see what answer will I get, as you can see in the bolded last part.
Thank you

**Comment by dzvoti** [comment]
> example <- df(admin_regions=c("Arusha","Dar es
> Salaam","Dodoma","Geita","Iringa","Kagera","Katavi","Kigoma","Kilimanjaro","Lindi"),

Hi @Hoyce509 , thank you for this attempt. I have noticed a typo when you create the dataframe. You used df(admin....) instead of data. Frame(admin...) like so. 

```r
# Code
example <- data.frame(admin_regions=c("Arusha","Dar esSalaam" ,"Dodoma" ,"Geita" ,"Iringa" ,"Kagera" ,"Katavi" ,"Kigoma" ,"Kilimanjaro" ,"Lindi") , population=c(1000000, 2000000, 3000000, 1500000, 1200000, 1100000, 800000,600000, 700000, 500000), households=c(100000, 150000, 200000, 75000, 60000, 55000, 40000, 30000, 35000, 25000))
summary(example) 

#Result
 admin_regions        population        households
 Length:10          Min.   : 500000   Min.   : 25000
 Class :character   1st Qu.: 725000   1st Qu.: 36250
 Mode  :character   Median :1050000   Median : 57500
                    Mean   :1240000   Mean   : 77000
                    3rd Qu.:1425000   3rd Qu.: 93750
                    Max.   :3000000   Max.   :200000  
> 
```

So well congratulations and well done for this attempt. Sometimes typos get the best of us but I have no doubt with time you will get better at debugging (finding small mistakes).

Liberty

**Comment by dzvoti** [comment]
> example <- df(admin_regions=c("Arusha","Dar es
> Salaam","Dodoma","Geita","Iringa","Kagera","Katavi","Kigoma","Kilimanjaro","Lindi"),

Hi @Hoyce509 , thank you for this attempt. I have noticed a typo when you create the dataframe. You used df(admin....) instead of data. Frame(admin...) like so. 

```r
# Code
example <- data.frame(admin_regions=c("Arusha","Dar esSalaam" ,"Dodoma" ,"Geita" ,"Iringa" ,"Kagera" ,"Katavi" ,"Kigoma" ,"Kilimanjaro" ,"Lindi") , population=c(1000000, 2000000, 3000000, 1500000, 1200000, 1100000, 800000,600000, 700000, 500000), households=c(100000, 150000, 200000, 75000, 60000, 55000, 40000, 30000, 35000, 25000))
summary(example) 

#Result
 admin_regions        population        households
 Length:10          Min.   : 500000   Min.   : 25000
 Class :character   1st Qu.: 725000   1st Qu.: 36250
 Mode  :character   Median :1050000   Median : 57500
                    Mean   :1240000   Mean   : 77000
                    3rd Qu.:1425000   3rd Qu.: 93750
                    Max.   :3000000   Max.   :200000  
> 
```

So well congratulations and well done for the attempt. Sometimes typos get the best of us but I have no doubt with time you will get better at debugging (finding small mistakes).

**Comment by Hoyce509** [comment]
Dear Liberty,
Thank you for the feedback.
Hope to see you tomorrow.

Regards,
Hoyce

**Comment by dzvoti** [comment]
> Dear Liberty, Thank you for the feedback. Hope to see you tomorrow. Regards, Hoyce
> […](#)

You are welcome @Hoyce509 . See you tomorrow.

**Comment by Hoyce509** [comment]
Great, thanks!
